[package]
name = "migrate-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.migrate]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.0"
default-features = false
