// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    migrate
    (
        init => init
        upgrade => upgrade
        migrate => migrate
        un_delegate => un_delegate
        withdraw => withdraw
        getSegld => segld
        getSegldSc => segld_sc
        getHegld => hegld
        getHegldSc => hegld_sc
        getHsegld => hsegld
        getHsegldSc => hsegld_sc
        getLiquidSc => liquid_sc
        getNftTicker => nft_ticker
        getPendingSegld => pending_segld
        getVirtualEgldAdded => virtual_egld_added
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
