// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    migrate
    (
        init => init
        upgrade => upgrade
        migrate => migrate
        un_delegate => un_delegate
        getSegld => segld
        getSegldSc => segld_sc
        getHegld => hegld
        getHegldSc => hegld_sc
        getHsegld => hsegld
        getHsegldSc => hsegld_sc
        getLiquidSc => liquid_sc
        getPendingSegld => pending_segld
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
